### ISSUE TITLE
swift 2 - updates failing

### ISSUE THREAD

**Issue by johndpope** [richzertuche/InceptionTouch#1]
![screen shot 2015-09-22 at 10 07 05 am](https://cloud.githubusercontent.com/assets/289994/10008413/afaa669a-6111-11e5-9132-4a5a259c0a22.png)

**Comment by johndpope** [comment]
this seems to fix it.
        var dreams = detector!.matchesInString(text, options: [], range: characterRange)
        for dream in dreams {
            if let dream_date = dream.date {
                self.inceptionTouchDelegate?.typeOfLink(0, link: "(dream_date)")
            } else if let dream_number = dream.phoneNumber {
                self.inceptionTouchDelegate?.typeOfLink(1, link: "(dream_number)")
            } else if let dream_url = dream.URL {
                self.inceptionTouchDelegate?.typeOfLink(2, link: "(dream_url)")
            } else if let dream_addres = dream.addressComponents {
                self.inceptionTouchDelegate?.typeOfLink(3, link: "(dream_addres)")
            }
        }

**Comment by richzertuche** [comment]
Thanks! @johndpope  
Fixed!
